<?xml version="1.0"?>
<robot name="sernew" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="width" value="0.10"/>
<xacro:property name="length" value="0.18"/>
<xacro:property name="radius_of_wheel" value="0.07"/>
<xacro:property name="gap_wheel" value="0.006"/>

<xacro:property name="caster_wheel_radius" value="${radius_of_wheel/2}"/>
<xacro:property name="caster_wheel_mass" value="0.0010"/>
</robot>